
spring:
  application:
     name: UserService
  datasource:
    url: jdbc:sqlserver://LAPTOP-855CFJLD;databaseName=workspace;;encrypt=true;trustServerCertificate=true
    username: admin
    password: admin123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
         dialect: org.hibernate.dialect.SQLServerDialect

server:
   port: 8008
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9001/eureka

logging:
  level:
    org:
      springframework:
        web:
          DEBUG